CREATE TABLE IF NOT EXISTS positions ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, side text NOT NULL CHECK (side IN ('long','short')), entry_price numeric NOT NULL, size numeric NOT NULL, stop_loss numeric, take_profit numeric, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')), opened_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_positions_user_id ON positions(user_id);
CREATE INDEX IF NOT EXISTS idx_positions_symbol ON positions(symbol);
CREATE POLICY "select_own_positions" ON positions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_positions" ON positions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_positions" ON positions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_positions" ON positions FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS trades ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, side text NOT NULL CHECK (side IN ('buy','sell')), price numeric NOT NULL, size numeric NOT NULL, fee numeric NOT NULL DEFAULT 0, pnl numeric NOT NULL DEFAULT 0, executed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_trades_user_id ON trades(user_id);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE POLICY "select_own_trades" ON trades FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_trades" ON trades FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_trades" ON trades FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_trades" ON trades FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS performance_snapshots ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, total_pnl numeric NOT NULL DEFAULT 0, win_rate numeric NOT NULL DEFAULT 0, sharpe numeric, max_drawdown numeric, snapshot_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE performance_snapshots ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_perf_user_id ON performance_snapshots(user_id);
CREATE POLICY "select_own_perf" ON performance_snapshots FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_perf" ON performance_snapshots FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_perf" ON performance_snapshots FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_perf" ON performance_snapshots FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS strategy_results ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, strategy text NOT NULL, timeframe text NOT NULL, win_rate numeric NOT NULL, confidence numeric NOT NULL, sample_size integer NOT NULL DEFAULT 0, last_run timestamptz NOT NULL DEFAULT now(), payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE strategy_results ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_strat_symbol_tf ON strategy_results(symbol, timeframe);
CREATE UNIQUE INDEX IF NOT EXISTS idx_strat_unique ON strategy_results(symbol, strategy, timeframe, COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE POLICY "read_strategy_results" ON strategy_results FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS ml_predictions ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), symbol text NOT NULL, timeframe text NOT NULL, prediction text NOT NULL, probability numeric NOT NULL, expected_move_pct numeric NOT NULL DEFAULT 0, model_version text NOT NULL, confidence text NOT NULL DEFAULT 'medium', payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE ml_predictions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_ml_symbol_tf ON ml_predictions(symbol, timeframe);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ml_unique ON ml_predictions(symbol, timeframe);
CREATE POLICY "read_ml_predictions" ON ml_predictions FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS trade_logs ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, timeframe text NOT NULL, side text NOT NULL CHECK (side IN ('buy','sell','neutral')), strategy text NOT NULL, entry numeric NOT NULL, exit numeric, stop_loss numeric, take_profit numeric, size numeric NOT NULL DEFAULT 0, pnl numeric NOT NULL DEFAULT 0, pnl_pct numeric NOT NULL DEFAULT 0, confidence numeric NOT NULL DEFAULT 0, regime text, explanation jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')), opened_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE trade_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_trade_logs_user_id ON trade_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_trade_logs_symbol ON trade_logs(symbol);
CREATE POLICY "select_own_trade_logs" ON trade_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_trade_logs" ON trade_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_trade_logs" ON trade_logs FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_trade_logs" ON trade_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS backtest_results ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, timeframe text NOT NULL, strategy text NOT NULL, metrics jsonb NOT NULL DEFAULT '{}'::jsonb, walk_forward jsonb NOT NULL DEFAULT '{}'::jsonb, monte_carlo jsonb NOT NULL DEFAULT '{}'::jsonb, last_run timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE backtest_results ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_backtest_symbol_tf ON backtest_results(symbol, timeframe);
CREATE UNIQUE INDEX IF NOT EXISTS idx_backtest_unique ON backtest_results(symbol, timeframe, strategy, COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE POLICY "read_backtest_results" ON backtest_results FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS risk_state ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, equity numeric NOT NULL DEFAULT 100000, starting_equity numeric NOT NULL DEFAULT 100000, daily_loss_used numeric NOT NULL DEFAULT 0, peak_equity numeric NOT NULL DEFAULT 100000, current_exposure_pct numeric NOT NULL DEFAULT 0, open_positions jsonb NOT NULL DEFAULT '[]'::jsonb, updated_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE risk_state ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_risk_state_user ON risk_state(user_id);
CREATE POLICY "select_own_risk_state" ON risk_state FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_risk_state" ON risk_state FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_risk_state" ON risk_state FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_risk_state" ON risk_state FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS ai_models ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL, architecture text NOT NULL CHECK (architecture IN ('dense','lstm','transformer')), hyperparams jsonb NOT NULL DEFAULT '{}'::jsonb, metrics jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'untrained' CHECK (status IN ('untrained','training','trained','failed')), input_features text[] NOT NULL DEFAULT '{}', output_classes text[] NOT NULL DEFAULT '{}', trained_at timestamptz, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE ai_models ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_ai_models_user ON ai_models(user_id);
CREATE POLICY "select_own_ai_models" ON ai_models FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_ai_models" ON ai_models FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_ai_models" ON ai_models FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_ai_models" ON ai_models FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS ai_predictions ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), model_id uuid REFERENCES ai_models(id) ON DELETE CASCADE, symbol text NOT NULL, input jsonb NOT NULL DEFAULT '{}'::jsonb, output jsonb NOT NULL DEFAULT '{}'::jsonb, confidence numeric NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE ai_predictions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_ai_pred_model ON ai_predictions(model_id);
CREATE INDEX IF NOT EXISTS idx_ai_pred_symbol ON ai_predictions(symbol);
CREATE POLICY "read_ai_predictions" ON ai_predictions FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS ai_training_data ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, source text NOT NULL DEFAULT 'manual', symbol text NOT NULL, features jsonb NOT NULL DEFAULT '{}'::jsonb, label numeric NOT NULL DEFAULT 0, label_type text NOT NULL DEFAULT 'classification' CHECK (label_type IN ('classification','regression')), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE ai_training_data ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_ai_train_user ON ai_training_data(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_train_symbol ON ai_training_data(symbol);
CREATE POLICY "select_own_ai_train" ON ai_training_data FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_ai_train" ON ai_training_data FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_ai_train" ON ai_training_data FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_ai_train" ON ai_training_data FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS profiles ( id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, first_name text NOT NULL DEFAULT '', last_name text NOT NULL DEFAULT '', phone text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', created_at timestamptz DEFAULT now() );
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "insert_ai_predictions" ON ai_predictions FOR INSERT TO authenticated WITH CHECK ( EXISTS (SELECT 1 FROM ai_models WHERE ai_models.id = ai_predictions.model_id AND ai_models.user_id = auth.uid()) );
CREATE POLICY "update_ai_predictions" ON ai_predictions FOR UPDATE TO authenticated USING ( EXISTS (SELECT 1 FROM ai_models WHERE ai_models.id = ai_predictions.model_id AND ai_models.user_id = auth.uid()) ) WITH CHECK ( EXISTS (SELECT 1 FROM ai_models WHERE ai_models.id = ai_predictions.model_id AND ai_models.user_id = auth.uid()) );
CREATE POLICY "delete_ai_predictions" ON ai_predictions FOR DELETE TO authenticated USING ( EXISTS (SELECT 1 FROM ai_models WHERE ai_models.id = ai_predictions.model_id AND ai_models.user_id = auth.uid()) );
CREATE POLICY "insert_backtest_results" ON backtest_results FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_backtest_results" ON backtest_results FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_backtest_results" ON backtest_results FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_ml_predictions" ON ml_predictions FOR INSERT TO authenticated WITH CHECK (false);
CREATE POLICY "update_ml_predictions" ON ml_predictions FOR UPDATE TO authenticated USING (false) WITH CHECK (false);
CREATE POLICY "delete_ml_predictions" ON ml_predictions FOR DELETE TO authenticated USING (false);
CREATE POLICY "insert_strategy_results" ON strategy_results FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_strategy_results" ON strategy_results FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_strategy_results" ON strategy_results FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS user_roles ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'user' CHECK (role IN ('user','trader','analyst','admin','super_admin')), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_role" ON user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_role" ON user_roles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_role" ON user_roles FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id AND role IN ('user','trader','analyst'));
CREATE TABLE IF NOT EXISTS alerts ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, type text NOT NULL CHECK (type IN ('price','ai_signal','risk','strategy')), symbol text NOT NULL, message text NOT NULL, severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','critical')), read boolean NOT NULL DEFAULT false, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_alerts_user_unread ON alerts(user_id) WHERE read = false;
CREATE INDEX IF NOT EXISTS idx_alerts_user_created ON alerts(user_id, created_at DESC);
CREATE POLICY "select_own_alerts" ON alerts FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_alerts" ON alerts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_alerts" ON alerts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_alerts" ON alerts FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS audit_logs ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, action text NOT NULL, resource text NOT NULL DEFAULT '', ip_address text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_audit_user_created ON audit_logs(user_id, created_at DESC);
CREATE POLICY "select_own_audit" ON audit_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_audit" ON audit_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS news_items ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), headline text NOT NULL, summary text NOT NULL DEFAULT '', source text NOT NULL DEFAULT '', url text UNIQUE, symbols text[] NOT NULL DEFAULT '{}', sentiment text NOT NULL DEFAULT 'neutral' CHECK (sentiment IN ('positive','negative','neutral')), sentiment_score numeric NOT NULL DEFAULT 0, published_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE news_items ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_news_published ON news_items(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_symbols ON news_items USING GIN(symbols);
CREATE POLICY "read_news" ON news_items FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS subscriptions ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, plan text NOT NULL DEFAULT 'free' CHECK (plan IN ('free','pro','institutional')), status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','cancelled','past_due')), started_at timestamptz NOT NULL DEFAULT now(), current_period_end timestamptz, created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_subscription" ON subscriptions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS user_settings ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, default_timeframe text NOT NULL DEFAULT '1h', risk_tolerance text NOT NULL DEFAULT 'moderate' CHECK (risk_tolerance IN ('conservative','moderate','aggressive')), theme text NOT NULL DEFAULT 'dark', notif_price_alerts boolean NOT NULL DEFAULT true, notif_ai_signals boolean NOT NULL DEFAULT true, notif_risk_warnings boolean NOT NULL DEFAULT true, notif_strategy_triggers boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_settings" ON user_settings FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_settings" ON user_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_settings" ON user_settings FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_settings" ON user_settings FOR DELETE TO authenticated USING (auth.uid() = user_id);
ALTER TABLE risk_state ADD COLUMN IF NOT EXISTS max_daily_loss_pct numeric NOT NULL DEFAULT 0.03, ADD COLUMN IF NOT EXISTS max_drawdown_pct numeric NOT NULL DEFAULT 0.20, ADD COLUMN IF NOT EXISTS max_exposure_pct numeric NOT NULL DEFAULT 0.40;
CREATE TABLE IF NOT EXISTS paper_positions ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, label text NOT NULL, side text NOT NULL DEFAULT 'long' CHECK (side IN ('long', 'short')), quantity numeric NOT NULL DEFAULT 0, entry_price numeric NOT NULL DEFAULT 0, stop_loss numeric, take_profit numeric, trailing_stop_pct numeric, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'pending')), order_type text NOT NULL DEFAULT 'market' CHECK (order_type IN ('market', 'limit', 'stop')), limit_price numeric, strategy text, ai_confidence numeric, opened_at timestamptz DEFAULT now(), closed_at timestamptz, close_price numeric, pnl numeric, pnl_pct numeric, notes text, created_at timestamptz DEFAULT now() );
ALTER TABLE paper_positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_positions" ON paper_positions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_positions" ON paper_positions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_positions" ON paper_positions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_positions" ON paper_positions FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS paper_trades ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, symbol text NOT NULL, label text NOT NULL, side text NOT NULL CHECK (side IN ('long', 'short')), quantity numeric NOT NULL DEFAULT 0, entry_price numeric NOT NULL DEFAULT 0, exit_price numeric NOT NULL DEFAULT 0, pnl numeric NOT NULL DEFAULT 0, pnl_pct numeric NOT NULL DEFAULT 0, strategy text, ai_confidence numeric, entry_time timestamptz DEFAULT now(), exit_time timestamptz DEFAULT now(), hold_duration_hours numeric, exit_reason text NOT NULL DEFAULT 'manual' CHECK (exit_reason IN ('manual', 'stop_loss', 'take_profit', 'trailing')), created_at timestamptz DEFAULT now() );
ALTER TABLE paper_trades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_trades" ON paper_trades FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_trades" ON paper_trades FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_trades" ON paper_trades FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_trades" ON paper_trades FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS journal_entries ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, trade_id uuid, symbol text NOT NULL, title text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', lessons_learned text NOT NULL DEFAULT '', tags text[] DEFAULT '{}', mood text CHECK (mood IS NULL OR mood IN ('confident', 'neutral', 'uncertain', 'anxious')), screenshot_url text, created_at timestamptz DEFAULT now() );
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_journal" ON journal_entries FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_journal" ON journal_entries FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_journal" ON journal_entries FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_journal" ON journal_entries FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS watchlists ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL, category text NOT NULL DEFAULT 'custom' CHECK (category IN ('crypto', 'forex', 'commodity', 'index', 'stock', 'favorites', 'custom')), is_default boolean NOT NULL DEFAULT false, created_at timestamptz DEFAULT now() );
ALTER TABLE watchlists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_watchlists" ON watchlists FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_watchlists" ON watchlists FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_watchlists" ON watchlists FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_watchlists" ON watchlists FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS watchlist_items ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), watchlist_id uuid NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE, symbol text NOT NULL, label text NOT NULL, market text NOT NULL DEFAULT 'crypto', display_order integer NOT NULL DEFAULT 0, added_at timestamptz DEFAULT now() );
ALTER TABLE watchlist_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_wl_items" ON watchlist_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM watchlists WHERE watchlists.id = watchlist_items.watchlist_id AND watchlists.user_id = auth.uid()));
CREATE POLICY "insert_own_wl_items" ON watchlist_items FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM watchlists WHERE watchlists.id = watchlist_items.watchlist_id AND watchlists.user_id = auth.uid()));
CREATE POLICY "update_own_wl_items" ON watchlist_items FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM watchlists WHERE watchlists.id = watchlist_items.watchlist_id AND watchlists.user_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM watchlists WHERE watchlists.id = watchlist_items.watchlist_id AND watchlists.user_id = auth.uid()));
CREATE POLICY "delete_own_wl_items" ON watchlist_items FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM watchlists WHERE watchlists.id = watchlist_items.watchlist_id AND watchlists.user_id = auth.uid()));
CREATE INDEX IF NOT EXISTS idx_pp_user_status ON paper_positions(user_id, status);
CREATE INDEX IF NOT EXISTS idx_pt_user_time ON paper_trades(user_id, exit_time DESC);
CREATE INDEX IF NOT EXISTS idx_je_user_time ON journal_entries(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wl_user ON watchlists(user_id);
CREATE INDEX IF NOT EXISTS idx_wli_list ON watchlist_items(watchlist_id, display_order);
CREATE TABLE IF NOT EXISTS alert_rules ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE, type text NOT NULL CHECK (type IN ('price_above', 'price_below', 'pct_move', 'rsi_above', 'rsi_below', 'macd_cross', 'ema_cross', 'pattern', 'structure_bos', 'structure_choch', 'ai_buy', 'ai_sell', 'ai_confidence', 'risk_exposure', 'risk_drawdown')), symbol text NOT NULL, condition text NOT NULL DEFAULT '', threshold numeric, severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')), enabled boolean NOT NULL DEFAULT true, message text NOT NULL DEFAULT '', metadata jsonb DEFAULT '{}', created_at timestamptz DEFAULT now(), triggered_at timestamptz );
ALTER TABLE alert_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_alert_rules" ON alert_rules FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "insert_own_alert_rules" ON alert_rules FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_alert_rules" ON alert_rules FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_alert_rules" ON alert_rules FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_ar_user_enabled ON alert_rules(user_id, enabled);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.positions TO authenticated;
GRANT ALL ON public.positions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trades TO authenticated;
GRANT ALL ON public.trades TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.performance_snapshots TO authenticated;
GRANT ALL ON public.performance_snapshots TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.strategy_results TO authenticated;
GRANT ALL ON public.strategy_results TO service_role;
GRANT SELECT ON public.strategy_results TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ml_predictions TO authenticated;
GRANT ALL ON public.ml_predictions TO service_role;
GRANT SELECT ON public.ml_predictions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trade_logs TO authenticated;
GRANT ALL ON public.trade_logs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.backtest_results TO authenticated;
GRANT ALL ON public.backtest_results TO service_role;
GRANT SELECT ON public.backtest_results TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_state TO authenticated;
GRANT ALL ON public.risk_state TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_models TO authenticated;
GRANT ALL ON public.ai_models TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_predictions TO authenticated;
GRANT ALL ON public.ai_predictions TO service_role;
GRANT SELECT ON public.ai_predictions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_training_data TO authenticated;
GRANT ALL ON public.ai_training_data TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alerts TO authenticated;
GRANT ALL ON public.alerts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_logs TO authenticated;
GRANT ALL ON public.audit_logs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.news_items TO authenticated;
GRANT ALL ON public.news_items TO service_role;
GRANT SELECT ON public.news_items TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.subscriptions TO authenticated;
GRANT ALL ON public.subscriptions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_settings TO authenticated;
GRANT ALL ON public.user_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.paper_positions TO authenticated;
GRANT ALL ON public.paper_positions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.paper_trades TO authenticated;
GRANT ALL ON public.paper_trades TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.journal_entries TO authenticated;
GRANT ALL ON public.journal_entries TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.watchlists TO authenticated;
GRANT ALL ON public.watchlists TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.watchlist_items TO authenticated;
GRANT ALL ON public.watchlist_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alert_rules TO authenticated;
GRANT ALL ON public.alert_rules TO service_role;